{% set version = "4.3.0a" %}

package:
  name: libspatialite
  version: {{ version }}

source:
  fn: libspatialite-{{ version }}.tar.gz
  url: http://www.gaia-gis.it/gaia-sins/libspatialite-{{ version }}.tar.gz
  sha256: 88900030a4762904a7880273f292e5e8ca6b15b7c6c3fb88ffa9e67ee8a5a499
  patches:
    # Skips 3 tests (check_extension, check_sql_stmt, and check_get_normal_zoom_extension_load) that are failing on OS X.
    # Re-visit this once a new release is out.
    - skip_failing_test.patch  # [osx]
    - makefile.vc.patch  # [win]
    - config-msvc.patch  # [win]
    - gg_extras.patch  # [win]

build:
  number: 14
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    - sqlite 3.13.*
    - geos 3.5.*
    - proj4 4.9.3
    - freexl
    - zlib 1.2.*
    - libxml2 2.9.*
    - pkg-config  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - sqlite 3.13.*
    - geos 3.5.*
    - proj4 4.9.3
    - freexl
    - zlib 1.2.*
    - libxml2 2.9.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

#test:
  #commands:
    #- conda inspect linkages -p $PREFIX libspatialite  # [not win]
    #- conda inspect objects -p $PREFIX libspatialite  # [osx]

about:
  home: https://www.gaia-gis.it/fossil/libspatialite/index
  license: LGPL-2.1
  summary: 'Extend the SQLite core to support fully fledged Spatial SQL capabilities.'

extra:
  recipe-maintainers:
    - danclewley
    - gillins
    - ocefpaf
